replicaCount: 1
image:
  repository: https://905418475251.dkr.ecr.us-east-1.amazonaws.com/moonfrog-test
  tag: ${BP_IMAGE_TAG}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# Add more configurations as needed
